### ISSUE TITLE
Create paper-plugin.yml

### ISSUE THREAD

**Issue by SlimeDog** [SlimeDog/PluginVersions#8]
Create [paper-plugin.yml](https://docs.papermc.io/paper/dev/getting-started/paper-plugins)

**Comment by SlimeDog** [comment]
At the same time, remove the gratuitous comment from the head of `plugin.yml`.

**Comment by SlimeDog** [comment]
This may do the trick, when appropriately massaged by maven.
```
name: ${project.name}
version: ${project.version}
api-version: 1.13
main: ${project.groupId}.${project.artifactId}.${project.name}
description: ${project.description}
authors: [drives_a_ford, SlimeDog]

commands:
  pluginversions:
    description: Commands for PluginVersions
    usage: <command> list | <command> reload
    aliases: [pv]
  pluginversions list:
    description: List loaded plugins and versions
    usage: <command> [page]
  pluginversions reload:
    description: Reload configuration file
    usage: <command>

permissions:
  pluginversions.*:
    description: Allows access to all PluginVersions commands
    children:
      pluginversions.list: true
      pluginversions.reload: true
  pluginversions.list:
    description: Allows you to retrieve PluginVersions listing
    default: op
  pluginversions.reload:
    description: Allows you to reload PluginVersions configuration
    default: op
```
